config/routes.rb
Rails.application.routes.draw do
  resources :message_users
  resources :friends
  get 'rooms/show'

  resources :messages

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  	
  mount ActionCable.server => '/cable'
end

app/models/message_user.rb
class MessageUser < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/controllers/message_users_controller.rb
class MessageUsersController < ApplicationController
  before_action :set_message_user, only: [:show, :edit, :update, :destroy]

  # GET /message_users
  # GET /message_users.json
  def index
    @message_users = MessageUser.all
  end

  # GET /message_users/1
  # GET /message_users/1.json
  def show
  end

  # GET /message_users/new
  def new
    @message_user = MessageUser.new
  end

  # GET /message_users/1/edit
  def edit
  end

  # POST /message_users
  # POST /message_users.json
  def create
    @message_user = MessageUser.new(message_user_params)

    respond_to do |format|
      if @message_user.save
        format.html { redirect_to @message_user, notice: 'Message user was successfully created.' }
        format.json { render :show, status: :created, location: @message_user }
      else
        format.html { render :new }
        format.json { render json: @message_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_users/1
  # PATCH/PUT /message_users/1.json
  def update
    respond_to do |format|
      if @message_user.update(message_user_params)
        format.html { redirect_to @message_user, notice: 'Message user was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_user }
      else
        format.html { render :edit }
        format.json { render json: @message_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_users/1
  # DELETE /message_users/1.json
  def destroy
    @message_user.destroy
    respond_to do |format|
      format.html { redirect_to message_users_url, notice: 'Message user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_user
      @message_user = MessageUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_user_params
      params.require(:message_user).permit(:message_id, :user_id)
    end
end

app/helpers/message_users_helper.rb
module MessageUsersHelper
end

app/views/message_users/_form.html.erb
<%= form_for(message_user) do |f| %>
  <% if message_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message_user.errors.count, "error") %> prohibited this message_user from being saved:</h2>

      <ul>
      <% message_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_id %>
    <%= f.text_field :message_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/message_users/edit.html.erb
<h1>Editing Message User</h1>

<%= render 'form', message_user: @message_user %>

<%= link_to 'Show', @message_user %> |
<%= link_to 'Back', message_users_path %>

app/views/message_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Message Users</h1>

<table>
  <thead>
    <tr>
      <th>Message Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @message_users.each do |message_user| %>
      <tr>
        <td><%= message_user.message.content %></td>
        <td><%= message_user.user.name %></td>
        <td><%= link_to 'Show', message_user %></td>
        <td><%= link_to 'Edit', edit_message_user_path(message_user) %></td>
        <td><%= link_to 'Destroy', message_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message User', new_message_user_path %>

app/views/message_users/new.html.erb
<h1>New Message User</h1>

<%= render 'form', message_user: @message_user %>

<%= link_to 'Back', message_users_path %>

app/views/message_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @message_user.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @message_user.user %>
</p>

<%= link_to 'Edit', edit_message_user_path(@message_user) %> |
<%= link_to 'Back', message_users_path %>